# Generated by Django 5.2.7 on 2025-11-07 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bagpack", "0003_bagpack_type_alter_bagpack_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="bagpack",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
