# Generated by Django 5.2.7 on 2025-11-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DummyModel",
        ),
    ]
