# Generated by Django 5.2.7 on 2025-10-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crochet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="bagpacks/")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Animal", "Animal"),
                            ("People", "People"),
                            ("Item", "Item"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
