# Generated by Django 5.2.7 on 2025-10-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crochet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crochet",
            name="image",
            field=models.ImageField(upload_to="crochets/"),
        ),
    ]
