# Generated by Django 5.2.7 on 2025-11-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crochet", "0002_alter_crochet_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="crochet",
            name="category",
            field=models.CharField(
                choices=[("animal", "animal"), ("people", "people"), ("item", "item")],
                default="animal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="crochet",
            name="type",
            field=models.CharField(
                choices=[("single", "single"), ("multi", "multi")],
                default="single",
                max_length=10,
            ),
        ),
    ]
