# Generated by Django 5.2.7 on 2025-10-28 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bagback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bagpack",
            name="season",
            field=models.CharField(
                choices=[
                    ("spring", "Spring"),
                    ("summer", "Summer"),
                    ("Autumn", "Autumn"),
                    ("winter", "Winter"),
                ],
                default=django.utils.timezone.now,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
