# Generated by Django 5.2.7 on 2025-11-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bagback", "0002_bagpack_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="bagpack",
            name="type",
            field=models.CharField(
                choices=[("single", "single"), ("multi", "multi")],
                default="single",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="bagpack",
            name="season",
            field=models.CharField(
                choices=[
                    ("spring", "spring"),
                    ("summer", "summer"),
                    ("autumn", "autumn"),
                    ("winter", "winter"),
                ],
                max_length=10,
            ),
        ),
    ]
